services:
  dev:
    build:
      context: .
      dockerfile: Containerfile.dev
    env_file:
      - .dev.env
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password1!"
      MSSQL_PID: Developer
    ports:
      - "1434:1433"